### ISSUE TITLE
Relative imports are not preserved

### ISSUE THREAD

**Issue by jbalsas** [metal/metal-tools-build-amd#1]
The current implementation of `resolveModuleSource` in [buildAmd](https://github.com/metal/metal-tools-build-amd/blob/master/lib/pipelines/buildAmd.js) does not preserve relative imports as opposed to the default [babelResolver:resolveModuleSrouce](https://github.com/jshanson7/babel-resolver/blob/master/lib/resolveModuleSource.js) default one.

For example, an import like

``` javascript
import foo from ./bar/foo;
```

will get transpiled to

``` javascript
define(['bar/foo'])
```

This will confuse loaders and makes it virtually impossible to switch from a default babel stack to one based on metal-tools.

Is there a specific reason to do it?

**Comment by eduardolundgren** [comment]
It should be fine to keep `./` in the module name. Is that common on AMD?

**Comment by jbalsas** [comment]
I don't know how common that could be, but I feel that if it's supported by default in Babel, we should probably behave in a similar way so you could switch between tools... 

In any case, I'll take a look at the loader again to get a better picture of the issue this is causing...

**Comment by eduardolundgren** [comment]
LGTM then. Let me know and I can merge it.

**Comment by jbalsas** [comment]
Hey @eduardolundgren, I think I could probably cheat the loader in the Liferay build to always disambiguate the path to the full module path, but that would be just a workaround for us.

I think we should have this merged in if not for anything else, for compatibility at least.

When you merge, could you make sure to update and publish `metal-cli` so I could finish the integration there?

Thanks!

**Comment by eduardolundgren** [comment]
It's released https://github.com/metal/metal-tools-build-amd/releases/tag/v0.1.0 but not published to npm, since I don't have privileges. Therefore, you need to use metal-cli from master until @mairatma gets back, bump metal-cli pointing to v0.1.0 and publish it. Let me know if you have any question.

**Comment by mairatma** [comment]
I've just published a new version of metal-cli with this :)
